export const FETCH_COURSES = "FETCH_COURSES";
export const FETCH_COURSES_PAGINATION = "FETCH_COURSES_PAGINATION";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_COURSE_CATEGORY = "FET__COURSE_CATEGORY";
export const FETCH_COURSE_DETAIL = "FETCH_COURSE_DETAIL";
export const FETCH_USERS_OF_COURSE = "FETCH_USERS_OF_COURSE";