export const FETCH_CREDENTIALS = "FETCH_CREDENTIALS";
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_PAGINATION = "FETCH_USERS_PAGINATION";
export const FETCH_USER_TYPE = "FETCH_USER_TYPE";
export const FETCH_USER_ON_TYPE = "FETCH_USER_ON_TYPE";